### ISSUE TITLE
Hi! where is ‘config’

### ISSUE THREAD

**Issue by dagongzhizheng** [neozhaoliang/surround-view-system-introduction#1]

**Comment by neozhaoliang** [comment]
抱歉之前提交的时候把 `config.py` 重命名成了 `paramsettings.py` 但是在 `surroundview.py` 里面没有及时改过来，已经修正了。

**Comment by dagongzhizheng** [comment]
多谢！不过还有一个问题，在stitch_images.py 文件的main()函数里有proj_mat = np.array(data["M"])一句，我看了下是读取那几个xxx.yaml文件的， 那里面只有"D","K"两个东西，并没有"M"这个字段。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Zhao Liang"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月20日(星期五) 下午4:55
收件人:&nbsp;"neozhaoliang/surround-view-system-introduction"<surround-view-system-introduction@noreply.github.com&gt;;
抄送:&nbsp;"中山靖王"<995883920@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [neozhaoliang/surround-view-system-introduction] Hi! where is ‘config’ (#1)





 
抱歉之前提交的时候把 config.py 重命名成了 paramsettings.py 但是在 surroundview.py 里面没有及时改过来，已经修正了。
