### ISSUE TITLE
问题请教-透视矩阵project_matrix 的获取

### ISSUE THREAD

**Issue by Quentin-xue** [neozhaoliang/surround-view-system-introduction#100]
楼主 您好
有个问题一直不明白，这里的dst_points是根据标定布的大小和位置，已经是固定的了，所以可以准确的将这个dst_points给定义出来。
![image](https://github.com/user-attachments/assets/4e246c81-d7c1-4a09-8ef1-b721bc7fd1dd)
src = np.float32(gui.keypoints)
dst = np.float32(dst_points)
camera_model.project_matrix = cv2.getPerspectiveTransform(src, dst)
还有一个链接
https://github.com/AriaTZY/Vehicle-Panoramic-View-Python?tab=readme-ov-file
![image](https://github.com/user-attachments/assets/74401cc5-8c5c-47b2-9271-b7acd2fef7d2)
中间说的，根据内参和外参计算（世界坐标系）的哪个位置，是不是跟您这里的 dst_points 是类似的？
能不能根据内参和外参把您的dst_points即project_keypoints 计算出来？
麻烦指导一下

**Comment by neozhaoliang** [comment]
不能。相机的内参和外参与标定布没有关系。

**Comment by Quentin-xue** [comment]
@neozhaoliang 
您好，再请教一下，我们现在想把这个环视应用在水上面，360安装到船上面。有什么好的方法用来获取透视矩阵吗？
