### ISSUE TITLE
关于实验小车如何获取投影矩阵的问题

### ISSUE THREAD

**Issue by Ansor-ZJJ** [neozhaoliang/surround-view-system-introduction#102]
您好，现在我有一辆与鞋盒差不多大小的小车，目前只有一块棋盘格标定板，也没有合适的环状标定布。我的计划是，现在小车周围画出设定好的范围矩形框，然后固定小车位置不动，然后再将标定板放到四个摄像头的可见区域中的预定位置，最后再选取指定关键点获取投影矩阵，这样方案可行吗？

**Comment by neozhaoliang** [comment]
打印四张纸

**Comment by Ansor-ZJJ** [comment]
> 把标定图案打印在四张纸上

请问一定需要四张纸同时摆放吗吗？我理解的是在求取投影矩阵的时候，棋盘格的作用是为了精确得到摄像头视角图中的关键点位置和鸟瞰图中对应的正确位置，如果保持四个摄像头的位置不变，用一张棋盘格依次放在四个摄像头面前，然后依次对四个摄像头求取投影矩阵不是一样的吗？

**Comment by neozhaoliang** [comment]
鱼眼相机矫正以后也有畸变，求解投影矩阵的时候应该选择尽可能大的范围。如果你的纸足够大也是可以的。

**Comment by Ansor-ZJJ** [comment]
> 鱼眼相机矫正以后也有畸变，求解投影矩阵的时候应该选择尽可能大的范围。如果你的纸足够大也是可以的。

明白了，感谢！

**Comment by Ansor-ZJJ** [comment]
> 鱼眼相机矫正以后也有畸变，求解投影矩阵的时候应该选择尽可能大的范围。如果你的纸足够大也是可以的。

还有个问题想请教一下，请问求解投影矩阵时候范围多大才算大呢？是相对于鱼眼相机原视场来说还是对于想要得到的鸟瞰图视野范围来说呢？如果我只需要得到小车四周一米左右的鸟瞰图视野范围，是否一个比较小的标定板和选择范围也是可以的呢？

**Comment by Ansor-ZJJ** [comment]
> 是指你选择的 4 个角点构成的四边形应尽可能该覆盖你的矫正图像

好的，感谢！
