### ISSUE TITLE
摄像头连接

### ISSUE THREAD

**Issue by EricChensir** [neozhaoliang/surround-view-system-introduction#103]
老师，您好！在运行test_cameras.py文件时，报错提示[ WARN:0@462.814] global cap_msmf.cpp:1768 CvCapture_MSMF::grabFrame videoio(MSMF): can't grab frame. Error: -1072875772
ERROR: failed read frame!
在连接两个摄像头时，第一个摄像头能够正常采集画面，切换第二个摄像头时，就无法正常读取画面，请问这是什么问题呢？两个摄像头均是logi c270。在linux环境下以及个人pc都出现了这种情况。

**Comment by neozhaoliang** [comment]
不太清楚，设备号正常吗？
