### ISSUE TITLE
重新设置输出鸟瞰图分辨率后，投影图像拼接出现有黑缝的情况

### ISSUE THREAD

**Issue by Ansor-ZJJ** [neozhaoliang/surround-view-system-introduction#104]
您好！我为了测试更小分辨率图像对代码运行速度的影响，使用的依旧是样例中的四个摄像头输入照片，将去畸变后图像的输出调整至了 640 * 512，将鸟瞰图输出分辨率调至 600 * 800，其它参数设置不变，让鸟瞰图中的1个像素对应0.5cm，投影关键点的选取做了一些调整，依旧是按照尽可能在返回的去畸变照片中的选取尽可能大的范围，但是最终产生了如下图的效果。
左下角区域没有相交也导致了计算权重矩阵出错的问题，请问产生这个问题的原因主要是什么呢？
![Uploading fliped_back.jpg…]()
![Uploading bird.png…]()

**Comment by Ansor-ZJJ** [comment]
![fliped_back](https://github.com/user-attachments/assets/02d76242-fb32-469e-a678-d2af8298cf6c)
![fliped_front](https://github.com/user-attachments/assets/7cac66e2-3854-4605-a3e4-37ad29280251)
![fliped_left](https://github.com/user-attachments/assets/618a9bac-1ea7-4ea6-a335-06f718158f19)
![fliped_right](https://github.com/user-attachments/assets/ced51024-1cbb-4181-94f7-fdab6e533031)
![bird](https://github.com/user-attachments/assets/b28541fd-21e5-40ae-856b-1a374955f4b3)

**Comment by neozhaoliang** [comment]
看起来，你的左右两边的投影计算是正确的，但是前后的投影图不对。你直观上就可以看出来，你前后的图像不是垂直的鸟瞰向下，有一些倾斜角度。

**Comment by Ansor-ZJJ** [comment]
> 看起来，你的左右两边的投影计算是正确的，但是前后的投影图不对。你直观上就可以看出来，你前后的图像不是垂直的鸟瞰向下，有一些倾斜角度。

感谢，我大概明白了
