### ISSUE TITLE
关于project_point以及xl,xr,yt,yb的计算

### ISSUE THREAD

**Issue by TANGLONG2** [neozhaoliang/surround-view-system-introduction#106]
非常感谢你的工作，但是我们拼出来的效果不是非常好，这可能是参数设置有一定问题，我想问一下，对于关于project_point以及xl,xr,yt,yb的计算，因为这里面涉及到了好几个数字，我想知道一下这些数字具体是什么意思？
![Uploading result.png…]()

**Comment by TANGLONG2** [comment]
shift_w = 300
shift_h = 300

# size of the gap between the calibration pattern and the car
# in horizontal and vertical directions
inn_shift_w = 52
inn_shift_h = 62

# total width/height of the stitched image
total_w = 400 + 2 * shift_w
total_h = 440 + 2 * shift_h

# four corners of the rectangular region occupied by the car
# top-left (x_left, y_top), bottom-right (x_right, y_bottom)
xl = shift_w + 120 + inn_shift_w
xr = total_w - xl
yt = shift_h + 120 + inn_shift_h
yb = total_h - yt
# ----------------这里我们的标定布长为440厘米，宽为400厘米，标定布距离车的位置长为52，宽为62，xl和yt中的120我们认为是标定布四个角也就是那四个重叠区域的长宽，project_keypoint应该是实际选点的坐标，但是这个坐标是以哪个为点为坐标原点的

**Comment by racoonwr** [comment]
@TANGLONG2 您好，我们也碰到拼接效果不好的情况，想跟您请教下怎么解决的
