### ISSUE TITLE
实时运行时间优化

### ISSUE THREAD

**Issue by winterhorse** [neozhaoliang/surround-view-system-introduction#11]
CPU运行两次remap时间消耗太多，可否用GPU优化，如OpenGL或OpenCL？

**Comment by neozhaoliang** [comment]
可以用查找表或者缩小图片分辨率来优化吧。用 opengl 怎么做校正呢。

**Comment by winterhorse** [comment]
OpenGL矫正有两个思路：
1. 把内参和畸变系数传入shader进行计算
2. 利用查找表将对应的顶点和纹理对应就好了

关键是需要两次remap，需要做两次插值。没有想好怎么用OpenGL完成两次查表。

**Comment by neozhaoliang** [comment]
AGX Xavier 有 cuda 加速。你可以用 taichi 这个库试试，自动并行并且编译为 cuda 加速。
笔记本上的话，如果支持 cuda 也是一样的，否则就会编译为 opengl 进行加速。

**Comment by winterhorse** [comment]
我用的是嵌入式平台，有GPU，支持OpenGL但不支持cuda

**Comment by neozhaoliang** [comment]
@winterhorse 请问如果你运行成功的话，是否介意放一张效果图上来，我作为用户案例在 readme 中引用？
