### ISSUE TITLE
楼主你好 在实车上做实验是一定要csi摄像头吗 usb摄像头不行吗

### ISSUE THREAD

**Issue by Lukas88664** [neozhaoliang/surround-view-system-introduction#17]
想在实车上做一下实验 另外 相机买的免驱动 是还需要自己写驱动才能在ubuntu中获取信息吗

**Comment by Lukas88664** [comment]
老哥 你的相机型号能在这里说一下吗

**Comment by rainyfeeling** [comment]
USB 摄像头是支持的。需要用--no_gst 选项。

**Comment by Lukas88664** [comment]
好的 那可以请教一下您的相机参数吗 我在采购 担心买错了型号做不出来

**Comment by rainyfeeling** [comment]
我用的是杰锐微通的1080p工业免驱摄像头。在ubuntu，树莓派上插上就能用。

**Comment by beihangzxm** [comment]
run_live_demo.py中代码 img = cv2.resize(birdview.get(), (300, 400))应该是设置的输出的分辨率吧，
但是4个输入摄像头的分辨率在哪里设置呢？
PS：之前提到加微信，是想交流这个项目的同时顺便看看有没有其他项目可以交流或者合作的

**Comment by beihangzxm** [comment]
> 我用的是杰锐微通的1080p工业免驱摄像头。在ubuntu，树莓派上插上就能用。

run_live_demo.py中代码 img = cv2.resize(birdview.get(), (300, 400))应该是设置的输出的分辨率吧，
但是4个输入摄像头的分辨率在哪里设置呢？
PS：之前提到加微信，是想交流这个项目的同时顺便看看有没有其他项目可以交流或者合作的

**Comment by beihangzxm** [comment]
> -no_gst



> USB 摄像头是支持的。需要用--no_gst 选项。

运行run_live_demo.py的时候是用python run_live_demo.py --no_gst吗？我现在手里只有两个非鱼眼摄像头，目前没办法运行这个，也是在摄像头选型阶段

**Comment by beihangzxm** [comment]
@rainyfeeling

**Comment by rainyfeeling** [comment]
> run_live_demo.py中代码 img = cv2.resize(birdview.get(), (300, 400))应该是设置的输出的分辨率吧，

对的。

> 但是4个输入摄像头的分辨率在哪里设置呢？

需要修改run_live_demo.py的main()函数的第一句:
```diff
@@ -15,7 +15,7 @@ camera_models = [FisheyeCameraModel(camera_file, name) for camera_file, name in                                                                                  


 def main():
-    capture_tds = [CaptureThread(camera_id, flip_method)                                                                                                                          
+    capture_tds = [CaptureThread(camera_id, flip_method, resolution=(640, 480), use_gst=False)                                                                                    
                    for camera_id, flip_method in zip(camera_ids, flip_methods)]
     capture_buffer_manager = MultiBufferManager()
     for td in capture_tds:
```


> PS：之前提到加微信，是想交流这个项目的同时顺便看看有没有其他项目可以交流或者合作的

OK

**Comment by betterpig** [comment]
> 我用的是杰锐微通的1080p工业免驱摄像头。在ubuntu，树莓派上插上就能用。

你买的视角是多少度的，焦距是多。我买的180度左右两侧刚好覆盖标定布多一点，导致鸟瞰变换后看不到角落。
