### ISSUE TITLE
实车测试硬件咨询

### ISSUE THREAD

**Issue by haige-algo** [neozhaoliang/surround-view-system-introduction#19]
楼主你好，请问一下在实车测试的时候，你选用CSI摄像头，连接CSI摄像头的工控机分别是什么型号，方便的话麻烦告知一下，谢谢

**Comment by neozhaoliang** [comment]
是一家做硬件的供应商，把 AGX 封装了接 CSI 摄像头的外设，价格比较贵。淘宝上有专门做改装的，你可以咨询下，但是一般价格也要在裸 AGX 上 x2.
