### ISSUE TITLE
xxxx.yaml文件里面没有"M"这个字段

### ISSUE THREAD

**Issue by dagongzhizheng** [neozhaoliang/surround-view-system-introduction#2]
你好！stitch_images.py 脚本里的main()函数里有  这么一句 proj_mat = np.array(data["M"])可是我查看相关xxx.yaml文件，里面只有“K”，“D”两个字段，并没有“M”这个字段。

**Comment by neozhaoliang** [comment]
不知道你是否已经解决了这个问题？
这是因为你还没有进行 get_projection_map 这一步，这一步之后才会把投影矩阵 m 写入到 yaml 文件中。

**Comment by dagongzhizheng** [comment]
非常感谢，我知道了，正在试！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Zhao Liang"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月20日(星期五) 晚上6:45
收件人:&nbsp;"neozhaoliang/surround-view-system-introduction"<surround-view-system-introduction@noreply.github.com&gt;;
抄送:&nbsp;"中山靖王"<995883920@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [neozhaoliang/surround-view-system-introduction] xxxx.yaml文件里面没有"M"这个字段 (#2)





 
不知道你是否已经解决了这个问题？
 这是因为你还没有进行 get_projection_map 这一步，这一步之后才会把投影矩阵 m 写入到 yaml 文件中。

**Comment by dagongzhizheng** [comment]
我刚刚试了一下，执行get_projection_map这个脚本，点了4个点后，代码里有'd','q','13'三个选项，但是都没有把结果写进yaml文件里。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Zhao Liang"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月20日(星期五) 晚上6:45
收件人:&nbsp;"neozhaoliang/surround-view-system-introduction"<surround-view-system-introduction@noreply.github.com&gt;;
抄送:&nbsp;"中山靖王"<995883920@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [neozhaoliang/surround-view-system-introduction] xxxx.yaml文件里面没有"M"这个字段 (#2)





 
不知道你是否已经解决了这个问题？
 这是因为你还没有进行 get_projection_map 这一步，这一步之后才会把投影矩阵 m 写入到 yaml 文件中。

**Comment by neozhaoliang** [comment]
![2020-03-20 19-25-04屏幕截图](https://user-images.githubusercontent.com/23307174/77159560-8c764080-6ae0-11ea-879b-37ab598ab472.png)


点击完四个点之后，需要敲回车.

**Comment by dagongzhizheng** [comment]
非常感谢，搞定！





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Zhao Liang"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月20日(星期五) 晚上7:25
收件人:&nbsp;"neozhaoliang/surround-view-system-introduction"<surround-view-system-introduction@noreply.github.com&gt;;
抄送:&nbsp;"中山靖王"<995883920@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [neozhaoliang/surround-view-system-introduction] xxxx.yaml文件里面没有"M"这个字段 (#2)





 

 
点击完四个点之后，需要敲回车.
