### ISSUE TITLE
运行calibration时不能捕捉到12个点？

### ISSUE THREAD

**Issue by Lukas88664** [neozhaoliang/surround-view-system-introduction#20]
![图片](https://user-images.githubusercontent.com/75986265/110748318-855cbb00-827a-11eb-89e8-d592a81994ea.png)
进行标定时，终端输入 python run_calibrate_camera.py --no_gst 
无法捕捉到12个点 怎么办？ 我的是杰瑞微通的1080pusb相机 ，进行标定时终端该输入一行什么命令？

**Comment by NovemberFantasy** [comment]
请问是如何解决的

**Comment by Toasting-bit** [comment]
> 请问是如何解决的



> 请问是如何解决的

你当时怎么解决的啊

**Comment by Toasting-bit** [comment]
你当时咋解决的啊 @NovemberFantasy
