### ISSUE TITLE
鸟瞰图时间戳与输入图像对应

### ISSUE THREAD

**Issue by lhlawrence** [neozhaoliang/surround-view-system-introduction#22]
您好我想在输出鸟瞰图时同时输出处理图像的时间戳该怎么处理呢？我看到在给buffer传输图像的时候有输入时间戳数据但是后面好像没有时间戳的处理

**Comment by neozhaoliang** [comment]
这个时间戳并不具备多少真实价值，因为图像采集的时刻、经过 Opencv 缓冲的时刻误差比较大。我是不太推荐从软件上对齐时间戳。
