### ISSUE TITLE
鸟瞰图扭曲

### ISSUE THREAD

**Issue by 792864625** [neozhaoliang/surround-view-system-introduction#29]
老师您好，我按照您docs文档用C++做了复现，用您提供的参数和输入图基本复现了您docs文档中的结果。和您的结果基本是一模一样的
问题是：当我自己使用汽车和标定布按照相同的步骤计算鸟瞰图，发现鸟瞰图**大体上正确**，但是有**扭曲变形**，不像您的鸟瞰图结果标定布的边边都是**平直**的。请问您的团队在探索过程中遇到过这种问题吗？可能是啥原因造成的呢？

**Comment by 792864625** [comment]
老师，我复现您的项目时，得到的结果和您给的结果是一模一样的。

**Comment by 792864625** [comment]
![front_bird](https://user-images.githubusercontent.com/24285104/160736588-fcf65605-6750-4168-96dd-1ad315e2f32a.png)

**Comment by 792864625** [comment]
图中分别是我复现您的结果，和我自己项目中的鸟瞰图结果
![front_bird](https://user-images.githubusercontent.com/24285104/160736829-2d7fd94e-9d95-4f1c-8018-928e538b5a0b.png)
![front_bird](https://user-images.githubusercontent.com/24285104/160736862-2fc6cf80-430d-49d4-bdbb-fedb48cce5c2.png)

**Comment by neozhaoliang** [comment]
需要检查下标定参数的设置，以及标志点的选择是否正确？
