### ISSUE TITLE
老师您好，我碰到些问题需要帮助：图片的鸟瞰拼接正常，但是在运行run_live_demo时有时会出现图片中的错误，有时则不会

### ISSUE THREAD

**Issue by ysw124** [neozhaoliang/surround-view-system-introduction#32]
![2022-05-10 17-11-59 的屏幕截图](https://user-images.githubusercontent.com/90886941/167594545-ef2fe842-f697-45d4-a16f-158c74dbf2a1.png)
这是我碰到的问题报错，该问题有时会出现，有时则不会出现，不出现时会成功运行实时的鸟瞰环视

![BirdView Result_screenshot_10 05 2022](https://user-images.githubusercontent.com/90886941/167594145-13b8079f-9a98-4eff-b187-4ef977c64a85.png)
这是我修改参数后拼接的静态图片，希望老师可以看下如何解决上述问题，方便的话可以qq交流：2940538260，谢谢老师

**Comment by neozhaoliang** [comment]
你给的信息太少，我猜不出你的错误原因。

**Comment by X-NN** [comment]
我和你一样的问题，请问解决了吗

**Comment by wztyy99899** [comment]
怎么解决这个问题

**Comment by wztyy99899** [comment]
> ![2d354af668d94801.jpg](https://user-images.githubusercontent.com/45159444/178770764-490b7e27-9f04-448e-8754-7eb433407ed4.jpg)这么操作下试试，我的解决了~

我的也是两个大小不一样如何解决

**Comment by XYIYIYIJ** [comment]
你好，我想问一下这是多少度的全景摄像头呀？
