### ISSUE TITLE
关于基于单应性矩阵的测距

### ISSUE THREAD

**Issue by DWendou** [neozhaoliang/surround-view-system-introduction#33]
想问一下，怎么通过单应性矩阵得到相机前面的物体到相机的距离。目前物体只有鱼眼图像中的2d box框，大致得到物体到相机的距离，需要怎么算？求老师指点一下

**Comment by neozhaoliang** [comment]
利用标定可以得到一个图像到地面的射影矩阵，将 box 的底边中心投影到地面上，以此作为物体坐标？这个方法会把物体的距离估计的比真实的要近一些，而且需要结合超声和 Kalman 滤波使用。

**Comment by DWendou** [comment]
> 利用标定可以得到一个图像到地面的射影矩阵，将 box 的底边中心投影到地面上，以此作为物体坐标？这个方法会把物体的距离估计的比真实的要近一些，而且需要结合超声和 Kalman 滤波使用。

谢谢老师指点。具体操作：如果我用物体box底边中心(x,y)作为物体坐标，然后令z=1，直接用project_matrix乘[x,y,z]投影到鸟瞰图上，然后在鸟瞰图上计算欧式距离得到离车距离。如果不用超声和Kalman滤波误差会不会很大？谢谢老师。

**Comment by neozhaoliang** [comment]
看你的用途，用来泊车或者在车库里面自动驾驶的话够呛。它只能起到大致定位的效果。不用 Kalman 滤波的话如果出现 bounding box 跳变的情况你怎么处理呢？

**Comment by DWendou** [comment]
> 看你的用途，用来泊车或者在车库里面自动驾驶的话够呛。它只能起到大致定位的效果。不用 Kalman 滤波的话如果出现 bounding box 跳变的情况你怎么处理呢？

明白了，检测后面应该会接一个sort追踪器的，非常感谢老师的指点。

**Comment by 1kepingguo** [comment]
> > 看你的用途，用来泊车或者在车库里面自动驾驶的话够呛。它只能起到大致定位的效果。不用 Kalman 滤波的话如果出现 bounding box 跳变的情况你怎么处理呢？
> 
> 明白了，检测后面应该会接一个sort追踪器的，非常感谢老师的指点。

您好，方便加v请教一下嘛？wulgdelianglai
