### ISSUE TITLE
怎么直接得到从原始画面到投影画面的查找表

### ISSUE THREAD

**Issue by DWendou** [neozhaoliang/surround-view-system-introduction#34]
老师您好，您在文档doc.md中的-具体实现的注意事项-中提及到的第二点，“同理对于 project_matrix 也不难获得一个查找表”这句话不太理解? 从畸变图到校正图应用cv2.fisheye.initUndistortRectifyMap()结合相机内参和畸变系数得到查找表mapx，mapy，那从校正图到鸟瞰图的查找表new_map要用到哪个函数？得到这个new_map后怎么与mapx和mapy合并才能直接从原图到鸟瞰图。求老师指点，谢谢您了，之前打扰过您一次了，非常感谢。

**Comment by neozhaoliang** [comment]
如果你有一个射影变换的矩阵来将一个图像 A 变到 B，则你可以对 B 的每个像素，计算它在逆射影变换下在 A 中的原像，从而得到这个对应的查找表。

**Comment by DWendou** [comment]
> 如果你有一个射影变换的矩阵来将一个图像 A 变到 B，则你可以对 B 的每个像素，计算它在逆射影变换下在 A 中的原像，从而得到这个对应的查找表。

非常谢谢老师，按照您的思路，我已经解决了这个问题了。
