### ISSUE TITLE
请教一下，前面步骤一切正常，运行run_live_demo.py报错，是什么问题啊？如图，谢谢！。

### ISSUE THREAD

**Issue by X-NN** [neozhaoliang/surround-view-system-introduction#37]
![IMG_20220713_010549_edit_1367533522201224](https://user-images.githubusercontent.com/45159444/178552852-176d5117-f916-4ff4-867b-e073af3c294d.jpg)

**Comment by neozhaoliang** [comment]
你的问题解决了没有？如果解决的话，是否有兴趣贴一下效果图，我加到 readme 的用户案例里面？
