### ISSUE TITLE
运行run_live_demo.py一直提示没有摄像头

### ISSUE THREAD

**Issue by lq666** [neozhaoliang/surround-view-system-introduction#38]
现在提示ValueError: operands could not be broadcast together with shapes (500,1600) (550,500)
是分辨率问题么？

**Comment by SLBiuBiu** [comment]
> 现在提示ValueError: operands could not be broadcast together with shapes (500,1600) (550,500)
> 是分辨率问题么？

你好，你是怎么解决的呀
