### ISSUE TITLE
报错，怎么解决，是摄像头问题吗？

### ISSUE THREAD

**Issue by Wanaicq0603** [neozhaoliang/surround-view-system-introduction#39]
![image](https://user-images.githubusercontent.com/110968623/183848395-3dc101d2-f58f-4867-9616-fa9df25393a8.png)

这个是偶尔运行成功，但是总会有一个摄像头卡住，在该摄像头前放置物品，晃动手，都没反应

**Comment by xulingrui-dashuai** [comment]
我也是这个问题

**Comment by Wanaicq0603** [comment]
那你解决了吗？像是摄像头没打开，搞了好久

**Comment by neozhaoliang** [comment]
注意下是不是一个端口带了多个相机导致的供电和传输问题
