### ISSUE TITLE
想问下，笔记本和四个外接摄像头如何实现连接

### ISSUE THREAD

**Issue by shadoubuhuideyy** [neozhaoliang/surround-view-system-introduction#40]

**Comment by neozhaoliang** [comment]
你需要外接一个 hub 呀，不过你要注意供电和传输速率的问题，所以一个端口可能带不动 4 个摄像头。

**Comment by shadoubuhuideyy** [comment]
十分感谢您，
您的意思是用两个hub然后接电脑的两个端口，每个hub外接两个相机是否就可以实现了呢？再次感谢您





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "neozhaoliang/surround-view-system-introduction"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月31日(星期三) 下午5:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [neozhaoliang/surround-view-system-introduction] 想问下，笔记本和四个外接摄像头如何实现连接 (Issue #40)





 
你需要外接一个 hub 呀，不过你要注意供电和传输速率的问题，所以一个端口可能带不动 4 个摄像头。

**Comment by neozhaoliang** [comment]
应该是可以的

**Comment by shadoubuhuideyy** [comment]
好的，非常感谢您，祝您万事如意







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "neozhaoliang/surround-view-system-introduction"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月31日(星期三) 下午5:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [neozhaoliang/surround-view-system-introduction] 想问下，笔记本和四个外接摄像头如何实现连接 (Issue #40)





 
应该是可以的

**Comment by shadoubuhuideyy** [comment]
老师，还得麻烦您一下，万分抱歉，我想问下，我如果用四路视频采集卡或者两个拓展坞，是不都可以实现笔记本外接四路摄像头，四路视频采集卡是不更好一点，我主要也是采集四路视频做图像拼接处理，不好意思打扰了





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "neozhaoliang/surround-view-system-introduction"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月31日(星期三) 下午5:54
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [neozhaoliang/surround-view-system-introduction] 想问下，笔记本和四个外接摄像头如何实现连接 (Issue #40)





 
Closed #40 as completed.

**Comment by neozhaoliang** [comment]
比较难的是保证画面同步。只要能传回图像别的问题就不大。

**Comment by shadoubuhuideyy** [comment]
> 比较难的是保证画面同步。只要能传回图像别的问题就不大。

好的，感谢您了

**Comment by shadoubuhuideyy** [comment]
请问我这个笔记本外接四路相机，对笔记本有啥要求吗？集显的行不？i5-12500.集成显卡，16-512固态
