### ISSUE TITLE
摄像头推荐

### ISSUE THREAD

**Issue by yeyuanzheng177** [neozhaoliang/surround-view-system-introduction#41]
请问，有没有好的摄像头推荐，信号传输网线或者usb的。可以给个摄像头链接吗

**Comment by yeyuanzheng177** [comment]
请问标定板有没有图片呢

**Comment by neozhaoliang** [comment]
标定板可以直接淘宝买亚克力的板子，能报的话就选磨砂玻璃的。

**Comment by yeyuanzheng177** [comment]
好的，谢谢，现在有个问题再次请教一下 我们需要在很大的场景进行标定 比如大卡车，这就导致太长的usb传输线可能有信号传输的问题，对于这一点有什么好的解决方法呢

**Comment by neozhaoliang** [comment]
正规的项目不要用 usb 连接的摄像头，可以找专门做环视摄像头的厂家 （挺多的），然后让他们把线加长。

**Comment by yeyuanzheng177** [comment]
好的谢谢，很多厂家用的同轴线，接不进我们的计算平台，比较麻烦。感谢您的耐心指点。

**Comment by neozhaoliang** [comment]
淘宝上有些开发者卖自己做的板子，可以接同轴的摄像头。还有的封装了 AGX。预算不是问题的话可以试一下。
