### ISSUE TITLE
这里面是否有融合超声波雷达

### ISSUE THREAD

**Issue by jianghuatao1** [neozhaoliang/surround-view-system-introduction#42]
你好，doc目录image文件夹下的result.mp4文件看起来像是融合了超声波雷达，请问融合超声波雷达的这部分代码有开源吗

**Comment by neozhaoliang** [comment]
sorry 这部分代码没有放在 repo 里面。因为超声部分是交付以后在客户的车上开发的，代码我也没有保存。其实也不复杂，用的 python-can 做的。https://python-can.readthedocs.io/en/master/
