### ISSUE TITLE
基于OpenGL ES3.0做环视拼接

### ISSUE THREAD

**Issue by DWendou** [neozhaoliang/surround-view-system-introduction#44]
看到老师您更新了最新的README信息，您想基于TaiChi做一个加速，您觉得OpenGL加速会不会更好一点

**Comment by neozhaoliang** [comment]
用 Taichi 写也可以指定后端为 OpenGL 加速。如果你自己手写 OpenGL 的部分的话工作量还是挺大的。

**Comment by neozhaoliang** [comment]
如果你能让这个项目在你的车上跑起来的话，我们可以合作一下一起开发。我这里已经没有可以调试的设备了。

**Comment by DWendou** [comment]
我确实借鉴了您这个项目中的一些技巧，不过我用的是纯C++版本的，目前已经上车了，只是基于CPU有点慢，达不到帧数，所以也想做一些加速处理，目前是想基于OpenGL ES3.0来做加速。您说的设备是指什么？车载系统吗，我只是做算法这块的，硬件就不知道了。。。团队中其他成员在弄

**Comment by DWendou** [comment]
我确实借鉴了您这个项目中的一些技巧，不过我用的是纯C++版本的，目前已经上车了，只是基于CPU有点慢，达不到帧数，所以也想做一些加速处理，目前是想基于OpenGL ES3.0来做加速。您说的设备是指什么？车载系统吗，我只是做算法这块的，硬件就不知道了。。。团队中其他成员在弄

**Comment by neozhaoliang** [comment]
对显示效果要求不高的话，把图片分辨率调小一点，或者去掉亮度和色彩平衡就可以了。

**Comment by DWendou** [comment]
好的，谢谢老师的建议，我再试试

**Comment by maGnet2C-cmd** [comment]
您好，我也在尝试使用OpenGL做加速，但在去畸变步骤遇到了问题，能否麻烦给些建议，谢谢！
[https://github.com/neozhaoliang/surround-view-system-introduction/issues/57](url)
