### ISSUE TITLE
运行run_calibrate_camera.py 添加参数 -fishe--nogest 运行可以识别角点，但按c标定会出现如下错误，使用的是usb鱼眼相机。感谢老师

### ISSUE THREAD

**Issue by shadoubuhuideyy** [neozhaoliang/surround-view-system-introduction#45]
cv2.error: OpenCV(3.4.1) C:\projects\opencv-python\opencv\modules\calib3d\src\fisheye.cpp:1414: error: (-3) CALIB_CHECK_COND - Ill-conditioned matrix for input array 0 in function cv::internal::CalibrateExtrinsics

**Comment by shadoubuhuideyy** [comment]
@neozhaoliang

**Comment by neozhaoliang** [comment]
看提示似乎是你的输入图像不符合要求。你有没有调整标定板的位置多拍几张？

**Comment by shadoubuhuideyy** [comment]
感谢回复，我采用的是标定版不动，只移动相机的方式。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "neozhaoliang/surround-view-system-introduction"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月7日(星期一) 下午2:36
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [neozhaoliang/surround-view-system-introduction] 运行run_calibrate_camera.py 添加参数 -fishe--nogest 运行可以识别角点，但按c标定会出现如下错误，使用的是usb鱼眼相机。感谢老师 (Issue #45)





 
看提示似乎是你的输入图像不符合要求。你有没有调整标定板的位置多拍几张？

**Comment by neozhaoliang** [comment]
理论上这也可以。你是所有的标定都失败吗？

**Comment by shadoubuhuideyy** [comment]
对的 目前我只是在程序中做了如下修改添加了这几个参数：

运行可以进行角点提取，但是按C标定后，就会出现下方的错误：








------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "neozhaoliang/surround-view-system-introduction"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月7日(星期一) 下午3:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [neozhaoliang/surround-view-system-introduction] 运行run_calibrate_camera.py 添加参数 -fishe--nogest 运行可以识别角点，但按c标定会出现如下错误，使用的是usb鱼眼相机。感谢老师 (Issue #45)





 
理论上这也可以。你是所有的标定都失败吗？

**Comment by shadoubuhuideyy** [comment]
对的，我只是在parameters中添加 -i 3 -fisheye --no_gst ，参数，然后运行，可以捕捉到角点，但是按c标定后，显示如下错误。
OpenCV(3.4.1) Error: Internal error (CALIB_CHECK_COND - Ill-conditioned matrix for input array 0) in cv::internal::CalibrateExtrinsics, file C:\projects\opencv-python\opencv\modules\calib3d\src\fisheye.cpp, line 1414
Traceback (most recent call last):
  File "C:\Users\whd\Desktop\surround-view-system-introduction-master (4)\surround-view-system-introduction-master\run_calibrate_camera.py", line 191, in <module>
    main()
  File "C:\Users\whd\Desktop\surround-view-system-introduction-master (4)\surround-view-system-introduction-master\run_calibrate_camera.py", line 164, in main
    (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 30, 1e-6)
cv2.error: OpenCV(3.4.1) C:\projects\opencv-python\opencv\modules\calib3d\src\fisheye.cpp:1414: error: (-3) CALIB_CHECK_COND - Ill-conditioned matrix for input array 0 in function cv::internal::CalibrateExtrinsics

**Comment by shadoubuhuideyy** [comment]
@neozhaoliang
