### ISSUE TITLE
老师您好，我现在才学习这部分内容，因为实验室没有相关设备，所以想自己采购机器人小车和摄像头

### ISSUE THREAD

**Issue by zy199676** [neozhaoliang/surround-view-system-introduction#46]
请问机器人小车是采用树莓派AI视觉小车，摄像头的话买usb工业摄像头，直接将摄像头想办法装在小车上，然后进行相关学习就可以了是么。

**Comment by neozhaoliang** [comment]
@zy199676 是的，项目中那个小车也是用的 USB 摄像头。标定板打印的也是可以的，把打印出来的图案固定在一个板子上保证平整就行。
