### ISSUE TITLE
Could you tell me the angle of view of the camera you used? Or a model name.

### ISSUE THREAD

**Issue by blackCmd** [neozhaoliang/surround-view-system-introduction#48]
Could you tell me the angle of view of the camera you used? Or a model name.

I wasted a lot of money buying the wrong camera.

Plz help me...

**Comment by neozhaoliang** [comment]
If I remember correctly, the fisheye angle for the car is $190^{\circ}$, and it's a CSI camera. How large is your car, and how much is your budget?
