### ISSUE TITLE
拼接处出现重影是投影不精准导致？

### ISSUE THREAD

**Issue by CPFelix** [neozhaoliang/surround-view-system-introduction#49]
感谢作者的优秀工作！我尝试搭建一个简陋的系统，发现最后拼接的全景图拼接处的棋盘格总是会出现重影，我猜测是投影矫正有误差导致两张鸟瞰图拼接时无法对齐，经过像素权重计算后出现重影问题，这样理解不知是否正确？
另外有个想法，拼接时根据棋盘格对两张鸟瞰图进行匹配，这样就能保证不会出现重影问题，类似于一些常见的全景拼接方法，不知是否可行？
![BirdView](https://user-images.githubusercontent.com/32193197/211950330-1872b783-eeac-4f25-82d6-d21ef30a9827.jpg)

**Comment by neozhaoliang** [comment]
拼接出现重影的因素很多，任何一个环节出问题都可能导致这种结果。

1. 你的相机视野是否能够覆盖车周围？每个相机中两个标定板不能看起来形变太严重。
2. 你的投影参数设置正确否？标志点的坐标设置和选择正确否？
3. 每个相机画面在投影到地面后，看起来自然否？

我建议你先按照项目所给的图片和参数，手动复现一下我在文档中给出的拼接效果，确保正确理解整个过程。

**Comment by CPFelix** [comment]
感谢回答！你开源的结果我已经复现了，所以才自己搭建一套比较简陋的环境验证。
另外，投影矫正时-scale -shift的设置对最终投影结果影响挺大的，想问下如何设置才更合理？不同摄像头需要保持相同的参数吗？

**Comment by neozhaoliang** [comment]
这个设置的原则应该是让你的 region of interest 的区域尽可能位于相机视野中央。
不同相机这个参数是可以不同的，你可以从项目里面的相机 yaml 文件里面看到它们是不一样的。

**Comment by CPFelix** [comment]
我尝试设置不同的-scale -shift感觉对生成的鸟瞰图结果影响挺大，下面投影变换全部采用了-scale  1.5 1.5 -shift 10 20。另外我上传了各个步骤的图片，请看下是否正常？
原始鱼眼：
![back](https://user-images.githubusercontent.com/32193197/212545306-7a45dca8-b325-49c3-8b42-8b579cae94df.png)
![front](https://user-images.githubusercontent.com/32193197/212545311-2d2d20d8-a4c1-4720-a40a-8c0a49af3385.png)
![left](https://user-images.githubusercontent.com/32193197/212545314-a7d08d72-0b64-4436-b6ea-ac890eac3a47.png)
![right](https://user-images.githubusercontent.com/32193197/212545315-a2954367-76fa-4d3b-8aac-f0cd21ad4ae9.png)
畸变矫正：
![back_undistort](https://user-images.githubusercontent.com/32193197/212545405-2a9cb8ab-c417-4af2-a3b5-062c28e1c05f.png)
![front_undistort](https://user-images.githubusercontent.com/32193197/212545408-a0f14c67-8cec-4818-8904-1275bb5c7944.png)
![left_undistort](https://user-images.githubusercontent.com/32193197/212545411-4a1a499b-aedf-4005-8ac6-0ffee38ecf58.png)
![right_undistort](https://user-images.githubusercontent.com/32193197/212545418-ed74f846-bdee-4108-909c-00ecb5710846.png)
投影矫正：
![back](https://user-images.githubusercontent.com/32193197/212545438-dc80381a-85d3-42f3-86de-d19251b6b2b8.png)
![front](https://user-images.githubusercontent.com/32193197/212545443-4a08ef54-276f-4b2f-a6b2-861a1234f6ec.png)
![left](https://user-images.githubusercontent.com/32193197/212545444-096a1056-07ba-4562-9861-171488b162c8.png)
![right](https://user-images.githubusercontent.com/32193197/212545446-092286f6-672a-4931-846a-a95d89046817.png)

**Comment by neozhaoliang** [comment]
你的校正图质量是可以的，用来标定投影矩阵应该没有问题。
但是你投影后的图很歪，所以不能确定是不是那些距离参数的设置有问题，或者你实际点击的特征点和代码中设置的特征点不一致。

**Comment by CPFelix** [comment]
开源代码里采用手工点击4个投影点的方式，我之前猜测是自己鼠标点击不够准确导致，所以采用了cv2.findChessboardCorners去自动寻找每个摄像头中间的棋盘格最外四个角点作为采样的投影点（效果见下图），param_setting.py也提前计算并修改在实际坐标系位置。 
![16E48A77-347F-4ceb-9D0B-76EF8E3DCFD4](https://user-images.githubusercontent.com/32193197/212548865-12d3807a-179a-4f83-8a10-c946d321eca5.png)

**Comment by neozhaoliang** [comment]
你可以试试这样：将四个标定点之间的距离选的远一些，因为你的纸是有弯曲的，根据一个很小区域的四个点计算的投影矩阵用在整个区域上可能效果不好。

**Comment by CPFelix** [comment]
好的，有可能就是我的棋盘格太小了，单格才7厘米，因为手头最大就是A3纸…
之后我切换大点的棋盘格试一试效果，再答复你，感谢回答！

**Comment by CPFelix** [comment]
我将棋盘格由6*4变为6*8，投影点也由4*2变为6*10，最终拼接效果相比之前确实有所提升。
年后考虑定制一个像你项目里的环车棋盘布对实车进行标定。
![BirdView](https://user-images.githubusercontent.com/32193197/212605034-7776904a-ab5a-4d49-ab95-af6ff3cbbfe2.jpg)
另外，方便加个联系方式吗？ @neozhaoliang

**Comment by neozhaoliang** [comment]
我的微信 id 也是 neozhaoliang
看起来你右上角和左下角的纸有明显的弯曲。

**Comment by CPFelix** [comment]
是的，因为我用的标定纸拼接总归有一定误差，而且单格边长太小，年后定制一套好点的标定装备应该会效果更好吧。再次感谢帮助！
