### ISSUE TITLE
对于光照补偿计算12个权重系数的方式，有没有计算的资料可以参考呢，十分感谢

### ISSUE THREAD

**Issue by hanrui234** [neozhaoliang/surround-view-system-introduction#55]

**Comment by neozhaoliang** [comment]
我不认为计算 12 个权重系数是一个值得学习的方法，现在我来写的话绝对不会用这种方法。比较消耗计算资源，而且有强光的环境下也不好用。追求真实图像没什么意义，驾驶员能看清周围环境最重要。你可以用双边网络滤波，或者 tone mapping 就行。
