### ISSUE TITLE
run_calibrate_camera.py相机标定后，再run_get_projection_maps.py会默认畸变矫正嘛？180度相机标定畸变较严重，请问有什么建议吗？

### ISSUE THREAD

**Issue by amarafreey** [neozhaoliang/surround-view-system-introduction#56]
![image](https://user-images.githubusercontent.com/108453983/222913431-ce376a10-62b5-400d-85af-1130ddb3bd37.png)
![image](https://user-images.githubusercontent.com/108453983/222913502-0032009d-c21d-4477-9fa8-3cec8d6470a5.png)

**Comment by neozhaoliang** [comment]
这些在文档里面是有解释的。

**Comment by amarafreey** [comment]
谢谢老师，已经解决啦
















在 2023-03-24 13:32:31，"Zhao Liang" ***@***.***> 写道：

这些在文档里面是有解释的。
