### ISSUE TITLE
运行run_live_demo.py代码在birdview.get()卡住

### ISSUE THREAD

**Issue by Cys6p** [neozhaoliang/surround-view-system-introduction#58]

**Comment by Cys6p** [comment]
作者您好！我在复现您项目的过程时，前面都比较顺利，但是在运行run_live_demo.py时，代码卡在了 
while True:  
img = cv2.resize(birdview.get(), (300, 400))
这句中，之后我定位到了imagebuffer.py文件中class Buffer的get函数。
`    def get(self):
        # acquire semaphores
        self.clear_buffer_get.acquire()
        self.used_slots.acquire()
        self.queue_mutex.lock()
        data = self.queue.get()
        self.queue_mutex.unlock()
        # release semaphores
        self.free_slots.release()
        self.clear_buffer_get.release()
        # return item to caller
        return data
`代码在运行过程中在这个函数里进入了死循环，没有任何图像生成，也没有任何报错，请问您可以提供一些解决问题的思路吗？在此多谢！

**Comment by neozhaoliang** [comment]
你可以正常运行那个标定的脚本吗？如果可以，说明 buffer 类是没有问题的。可能出在别的地方
