### ISSUE TITLE
运行run_calibrate_camera.py脚本时出现问题

### ISSUE THREAD

**Issue by ZhuZak** [neozhaoliang/surround-view-system-introduction#59]
老师您好！
在已经正确连接鱼眼摄像头与虚拟机后，运行相机标定脚本run_calibrate_camera.py时为什么总是显示
Cannot open camera 0
cannot open device
错误。请问这种错误是因为没有正确修改相机设备号导致的吗？需要怎么解决呀，谢谢老师！

**Comment by liujinqing-tx** [comment]
> 老师您好！ 在已经正确连接鱼眼摄像头与虚拟机后，运行相机标定脚本run_calibrate_camera.py时为什么总是显示 Cannot open camera 0 cannot open device 错误。请问这种错误是因为没有正确修改相机设备号导致的吗？需要怎么解决呀，谢谢老师！

您好，能请教你后续是如何实现的吗
