### ISSUE TITLE
你好，我想问一下具体的环境配置中用到的库的版本？

### ISSUE THREAD

**Issue by ddcreating** [neozhaoliang/surround-view-system-introduction#62]
您好，在代码中您给的版本是python>=3, OpenCV>=3, PyQt没有版本的信息。
然后我用Anaconda3配置的版本是python=0.9， PyQt5=5.15，OpenCV=3.4，在运行第一个文件run_calibrate_camera.py时就总是报错，错误是：symbol _ZdlPvm version Qt_5 not defined in file libQt5Core.so.5 with link time reference
网上说的兼容的问题，我找了网上现存的方法也没有解决，所以想问问作者，你们的版本具体是什么？我再去试试看会不会出错，谢谢您！

**Comment by neozhaoliang** [comment]
你可以查一下这个repo 里的 issue 不？有不少人遇到类似的问题，似乎他们都解决了。

**Comment by ddcreating** [comment]
ok，我已经解决了，我之前给您发了邮件，谢谢您的回复。应该是系统中的QT版本的影响，
