### ISSUE TITLE
你好，请问拼接图像色彩矫正有更好的方法吗？

### ISSUE THREAD

**Issue by xuexigua** [neozhaoliang/surround-view-system-introduction#63]
开源的例子中图像有点过曝的问题。

**Comment by neozhaoliang** [comment]
现在我来做的话，会直接进行色调映射，而不是追求四个相机的画面亮度完全一致。这个对算力影响比较大。当然如果你是用 OpenGL 跑在 GPU 上的话那就可以继续用。
