### ISSUE TITLE
Images used for projection

### ISSUE THREAD

**Issue by Sadat75** [neozhaoliang/surround-view-system-introduction#64]
Thank you for sharing the repository. I was wondering if you could share the left and right images you have used to choose the four points for projection.

**Comment by JaiKumar-Singh** [comment]
Hi @Sadat75 , It seems you had successfully run the code. Can you please share the Fisheye dataset used in this code or even the output video of "car.mp4"(with original resolution 1200x1600)?
Any help will be much appreciated!
