### ISSUE TITLE
关于4个摄像头占用带宽的问题

### ISSUE THREAD

**Issue by SLBiuBiu** [neozhaoliang/surround-view-system-introduction#65]
您好，大佬！现在我正在复现您的项目，关于4个USB摄像头占用带宽太大，两个就超了USB2.0的480Mbps。我之前有遇到过这个问题，我的解决办法是在capture_thread.py中的connect_camera方法里使用self.cap.set(cv2.CAP_PROP_FOURCC, cv2.VideoWriter_fourcc(*"MJPG"))将默认的编码改为MJPG，可以大大的降低带宽。
在test_cameras.py中同样也是这行代码
我实际测试一个USB口是可以带动4个摄像头的，但是实际带宽我没有计算过。

**Comment by neozhaoliang** [comment]
赞！这是个很有用的发现，可以麻烦你提个 PR 不？

**Comment by neozhaoliang** [comment]
没问题。

SLBiuBiu ***@***.***> 于2023年8月17日周四 20:32写道：
