### ISSUE TITLE
Cannot open camera 2

### ISSUE THREAD

**Issue by rwb1123** [neozhaoliang/surround-view-system-introduction#67]
python run_calibrate_camera.
py -i 2 -grid 9x6 -o fisheye.yaml  --resolution 1280x720  --fisheye
Cannot open camera 2
cannot open device

**Comment by SLBiuBiu** [comment]
What operating system are you using?

**Comment by neozhaoliang** [comment]
检查一下你的设备 2 是否对应相机，并且在 usb 相机的情况下加上 --no_gst 参数。

**Comment by rwb1123** [comment]
Ubuntu18.04  用的4个usb摄像头

**Comment by SLBiuBiu** [comment]
> Ubuntu18.04 用的4个usb摄像头
可能是这个ID没有对应这个相机，你可以执行[test_cameras.py](https://github.com/neozhaoliang/surround-view-system-introduction/blob/master/test_cameras.py) 注意看打印的相机列表，这个列表是可以打开相机的ID，但是他的范围只从0-24。
你可以执行 ls  /dev/video* 看一下相机设备，一个USB相机可能会生成两个，其中一个是虚拟的。例如你接了两个相机，执行命令之后的结果应该是 
/dev/video0  /dev/video1 /dev/video2  /dev/video3 其中可能0，2才是真正的相机ID

**Comment by rwb1123** [comment]
您好运行完&nbsp; 出现这个问题是什么导致的？







------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年11月9日(星期四) 下午5:39
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [neozhaoliang/surround-view-system-introduction] Cannot open camera 2 (Issue #67)





  
Ubuntu18.04 用的4个usb摄像头
 可能是这个ID没有对应这个相机，你可以执行test_cameras.py 注意看打印的相机列表，这个列表是可以打开相机的ID，但是他的范围只从0-24。
 你可以执行 ls  /dev/video* 看一下相机设备，一个USB相机可能会生成两个，其中一个是虚拟的。例如你接了两个相机，执行命令之后的结果应该是
 /dev/video0  /dev/video1 /dev/video2  /dev/video3 其中可能0，2才是真正的相机ID

**Comment by SLBiuBiu** [comment]
什么问题？

**Comment by rwb1123** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "neozhaoliang/surround-view-system-introduction"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月9日(星期四) 晚上7:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [neozhaoliang/surround-view-system-introduction] Cannot open camera 2 (Issue #67)





 
什么问题？

**Comment by SLBiuBiu** [comment]
看不到你的问题......

**Comment by rwb1123** [comment]
***@***.***:~/Downloads/surround1$&nbsp;python&nbsp;surroundview.py
[INFO]&nbsp;openning&nbsp;camera&nbsp;devices.
[INFO]&nbsp;loading&nbsp;camera&nbsp;intrinsic&nbsp;parameters...
[INFO]&nbsp;loading&nbsp;weight&nbsp;matrices...
Traceback&nbsp;(most&nbsp;recent&nbsp;call&nbsp;last):
File&nbsp;"surroundview&nbsp;py",&nbsp;Line&nbsp;189,&nbsp;in&nbsp;‹modules
main()
File&nbsp;"surroundview&nbsp;py",&nbsp;line&nbsp;103,&nbsp;in&nbsp;main
frame&nbsp;=&nbsp;cv2.&nbsp;remap(frame,&nbsp;map1,&nbsp;map2,&nbsp;interpolation=cv2.&nbsp;INTER_LINEAR,&nbsp;border&nbsp;ode=cv2.&nbsp;BORDER_CONSTANT)
cv2.&nbsp;error:&nbsp;OpenCV(4.5.5)&nbsp;/io/opencv/modules/improc/src/imgwarp.cpp:668:&nbsp;error:
(-215:&nbsp;Assertion&nbsp;failed)&nbsp;!ssize.&nbsp;empty()&nbsp;in&nbsp;function&nbsp;'remapBilinear'






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年11月9日(星期四) 晚上7:06
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [neozhaoliang/surround-view-system-introduction] Cannot open camera 2 (Issue #67)





 
看不到你的问题......

**Comment by SLBiuBiu** [comment]
加vx吧，这看的费劲，17330722027

**Comment by SLBiuBiu** [comment]
> 4个usb摄像头 同时插入四个摄像头，有一个可以检测到，但是不工作，请问如何降低带宽 ？

1.打开相机使用mjpg压缩，一个USB控制器链接两个摄像头
2.问USB摄像头生产厂家要降低带宽的固件
3.PCIE拓展USB（这个我没试过）

**Comment by rwb1123** [comment]
您好 请问有没有 试过使用两个CSI摄像头和两个USB摄像头的组合来实现？

**Comment by SLBiuBiu** [comment]
> 您好 请问有没有 试过使用两个CSI摄像头和两个USB摄像头的组合来实现？
> 
> 

没有
