### ISSUE TITLE
python run_live_demo.py，有的时间可以运行成功。但却有些时候报错ValueError: operands could not be broadcast together with shapes (0,170) (71,78)，不能一直运行成功。是什么原因？

### ISSUE THREAD

**Issue by A-shark-A** [neozhaoliang/surround-view-system-introduction#68]

**Comment by neozhaoliang** [comment]
你用的是 usb 相机还是 csi 相机？

**Comment by rwb1123** [comment]
![Uploading C]P7SH]G[@7J[M(281IDMXA.png…]()

**Comment by rwb1123** [comment]
python run_live_demo.py  出现  corrupt JPEG data：5 extraneous bytes before marker 0xd9

**Comment by neozhaoliang** [comment]
@rwb1123 你提 issue，不描述任何自己使用的环境，也不贴完整的报错信息，指望一句话让别人给你解决？

**Comment by rwb1123** [comment]
ubuntu18.04  AGX Xavier  4个usb摄像头  运行完python run_live_demo.py 出现 corrupt JPEG data：5 extraneous bytes before marker 0xd9，请问是出现了什么问题？

**Comment by rwb1123** [comment]
请问ubuntu18.04 AGX Xavier 4个usb摄像头 运行完python run_live_demo.py ，出现以下
masterS python run_live_demo.py
Corrupt JPEG data:10 extraneous bytes before marker 0xd9
Corrupt JPEG data:2extraneous bytes before marker 0xd9
Corrupt JPEG data:3 extraneous bytes before marker 0xd9
