### ISSUE TITLE
Fisheye Dataset Required

### ISSUE THREAD

**Issue by JaiKumar-Singh** [neozhaoliang/surround-view-system-introduction#78]
Hi @neozhaoliang , can you please provide the whole fisheye dataset used in this code for front,left,right,back images.

**Comment by neozhaoliang** [comment]
Currently I have only the four static images saved, the video files are missing

**Comment by JaiKumar-Singh** [comment]
Thanks for the quick reply. Any help with the dataset would be much appreciated(may it be sets of four static images or video files ) . Amazing work BTW.

**Comment by JaiKumar-Singh** [comment]
Hi @neozhaoliang , The resolution of video at path"surround-view-system-introduction/doc/img/car.mp4" is 640x480 but in the en.md you mentioned that bird's eye view resolution is 1200x1600(I suppose you have uploaded a compressed version). If you have the original version of the video can you please share the path? I am trying to generate input images from the video using inverse of the projection matrix you have provided in the .yaml files. Thank you for the help.
