### ISSUE TITLE
This is a question about camera resolution.

### ISSUE THREAD

**Issue by eunjaechoi** [neozhaoliang/surround-view-system-introduction#79]
You used a camera resolution of 960x640, but I plan to develop using a resolution of 1920x1024. If I only change the camera resolution and use it, are there any parameters that need to be changed?

Please answer about my question.
Thank you.

**Comment by neozhaoliang** [comment]
There are a few parameters in `param_settings.py` you need to modify to suit your case.

**Comment by eunjaechoi** [comment]
Hello neozhaoliang!
Thank you for your comment.
When I checked `param_setting.py`, It seemed like shift_w, shift_h, inn_shift_w, and inn_shift_h could be modified.
Could you please tell me the parameters that need to be set depending on the resolution?

**Comment by neozhaoliang** [comment]
I think not. You don't need to manually change resolution settings inside the folder `surround_view`.

**Comment by eunjaechoi** [comment]
@neozhaoliang 
understand! 
Thank you for your reply~!
