### ISSUE TITLE
鱼眼摄像头内参

### ISSUE THREAD

**Issue by winterhorse** [neozhaoliang/surround-view-system-introduction#8]
鱼眼摄像头的内参可以调用OpenCV等进行计算，也可以由摄像头生成厂家给出，这两者那个更为准确呢？

**Comment by neozhaoliang** [comment]
理论上厂家更准，但是我觉得在实际应用上区别不大。厂家能提供焦距的准确信息的话更好，可以制作 LUT 表。

**Comment by winterhorse** [comment]
计算内参的时候可以计算矫正的总体误差和投影误差，可以通过误差判断内参的矫正质量。有没有类似的参数可以评价拼接后的质量？

**Comment by neozhaoliang** [comment]
标定板/标定布图案清楚，无虚影模糊即可。
