### ISSUE TITLE
camera

### ISSUE THREAD

**Issue by yang-kuo** [neozhaoliang/surround-view-system-introduction#82]
请问一下普通的单目相机可以实现吗，还想再问一下run_get_projection_maps.py里面的scale和shift参数怎么设置的

**Comment by neozhaoliang** [comment]
普通相机的视角不够宽，放在侧面的话大概率不能覆盖车的前后。
scale 和 shift 参数你自己标定的时候怎么舒服怎么来。

**Comment by yang-kuo** [comment]
好的谢谢您，最近想实现这个功能，在看你的代码，有些地方还没有看明白。

**Comment by zheng0116** [comment]
我想请问下相机是多少度鱼眼相机？

**Comment by neozhaoliang** [comment]
文档里有相机型号
