### ISSUE TITLE
user gallery

### ISSUE THREAD

**Issue by neozhaoliang** [neozhaoliang/surround-view-system-introduction#83]
![1348501005](https://github.com/neozhaoliang/surround-view-system-introduction/assets/23307174/4481e70a-771c-4341-8c77-ca609c74f36f)

**Comment by lifei68** [comment]
请问你有修改什么地方吗，我按步骤调试不了那么好的拼接效果

**Comment by neozhaoliang** [comment]
这是某个用户自己部署得到的效果，也是有瑕疵的（有一个黑线他标定的时候没有覆盖到）。
这个 issue 是想整理用户的使用案例。

**Comment by lifei68** [comment]
我想请问一下，摄像头放置要求，要严格设置的各个距离是吗，我按照设定距离，左右侧一直调不出来咋会事，拼接效果不好。

**Comment by lifei68** [comment]
![BirdView Result_screenshot_20 03 2024](https://github.com/neozhaoliang/surround-view-system-introduction/assets/67627988/8fef9a83-2adf-420f-b725-8d4496fc3678)

**Comment by neozhaoliang** [comment]
这个用户也出现过你的问题。你检查一下是否是这个原因：在标定的时候，你选择的点不能集中在图像中心，因为鱼眼图像即便矫正了，边缘误差是比较大的，要让 opencv 尽可能在全局范围内算一个合适的投影矩阵。

**Comment by lifei68** [comment]
缩放和平移有什么技巧吗，因为左右侧图像的边缘处特别容易畸变，很难调好

**Comment by neozhaoliang** [comment]
只要你自己标定的时候，能够清楚看到标志点就行。shift 和 scale 对最终的拼接质量没有影响。

**Comment by lifei68** [comment]
那拼接质量和重叠区域是否包括，取决于什么？请教了，感谢

**Comment by lifei68** [comment]
左右两侧的图像投影为什么我这怎么都调整不好，无法使得四个角拼接好

**Comment by neozhaoliang** [comment]
@SLBiuBiu 您好，我正在收集用户案例，您是否介意把您拼接以后的效果图分享出来让大家看到？（有视频的话也很棒）。发在这个 issue 下面即可。我会更新到 README 里面。

**Comment by SLBiuBiu** [comment]
> @SLBiuBiu 您好，我正在收集用户案例，您是否介意把您拼接以后的效果图分享出来让大家看到？（有视频的话也很棒）。发在这个 issue 下面即可。我会更新到 README 里面。



您好，这是拼接的效果图，还是有点瑕疵的，视频的话，我这边没有录制过。
![birdview](https://github.com/neozhaoliang/surround-view-system-introduction/assets/57995003/e47a73cb-8367-4521-8ca5-27a7038a53e9)

**Comment by neozhaoliang** [comment]
@SLBiuBiu  看起来是选的四个点覆盖的矩形范围不够大。也许可以试试让四个点尽可能覆盖整个画面？

**Comment by SLBiuBiu** [comment]
@neozhaoliang 这个我没有试过，我是按照您给的参数设置的。

**Comment by neozhaoliang** [comment]
好的。

**Comment by lifei68** [comment]
![Uploading Bird's View_screenshot_25.03.2024.png…]()
![Uploading Bird's View_screenshot_25.03.2024-back.png…]()
![Uploading Bird's View_screenshot_25.03.2024-left.png…]()
![Uploading Bird's View_screenshot_25.03.2024-right.png…]()
![Uploading BirdView Result_screenshot_22.03.2024.png…]()

**Comment by lifei68** [comment]
我这个四个角处感觉好像还是有点问题
![BirdView Result_screenshot_25 03 2024-result](https://github.com/neozhaoliang/surround-view-system-introduction/assets/67627988/b5960aaa-f546-4bdf-b1b8-9aa1ced86016)

**Comment by neozhaoliang** [comment]
看起啦你地面上的黄线没有对齐？

**Comment by lifei68** [comment]
是的

**Comment by lifei68** [comment]
其实每次调整shift 和 scale 对最终拼接有影响

**Comment by neozhaoliang** [comment]
啊是的。因为 shift 和 scale 不同，呈现在你画面中心的区域就不同。不同的区域畸变程度不一样，所以投影以后效果也不太一样。

**Comment by neozhaoliang** [comment]
其实你的标定布是有些皱巴的。这个可能会导致误差。用塑料板或者亚克力做标定板精度就挺好，也不贵。

**Comment by lifei68** [comment]
还想请教个问题，在跑run_live_demo.py时候，有时候能跑通，有时候跑不通原因是什么；另外我从开始都调整为1920*1080的分辨率，最后得到的masks和weights也跑不通，显示grayA，mask尺寸大小不匹配

**Comment by neozhaoliang** [comment]
这个问题很多人报过，但我没遇到过，也不清楚具体原因。一种猜测是用户使用的是 USB 相机，usb 相机的设备号是上电的时候分配的，每次设备上电顺序不一样会导致设备号不同，所以报 bug 了。解决方法应该是固定设备号和相机的映射关系。

**Comment by lifei68** [comment]
![1711419627088](https://github.com/neozhaoliang/surround-view-system-introduction/assets/67627988/e4fa1e31-49b5-4f6b-9824-4623bd6d3068)
graya的值不是很稳定，总会变来变去

**Comment by neozhaoliang** [comment]
@lifei68 你的 shape 错误的问题解决了吗？如果找到原因的话，可否告知，我好加在文档里面？

**Comment by wycrystal** [comment]
> 我这个四个角处感觉好像还是有点问题 ![BirdView Result_screenshot_25 03 2024-result](https://github.com/neozhaoliang/surround-view-system-introduction/assets/67627988/b5960aaa-f546-4bdf-b1b8-9aa1ced86016)

请问你这个问题后来解决了吗？是什么原因导致的呢？
