### ISSUE TITLE
您好，我想和您探讨一下，这个代码是否支持不同数量的摄像头？比如6个？

### ISSUE THREAD

**Issue by liumarcus70s** [neozhaoliang/surround-view-system-introduction#84]
如题，比如这样的相机分布，这段代码能否支持？
![未命名绘图](https://github.com/neozhaoliang/surround-view-system-introduction/assets/8784986/86f5a8ca-c849-4772-9089-096549e3282e)

**Comment by neozhaoliang** [comment]
不支持。这个你需要自己修改代码。

**Comment by ptxaxx** [comment]
请问您解决6个相机的拼接方式了吗？
