### ISSUE TITLE
请教大佬关于自动对齐的思路

### ISSUE THREAD

**Issue by notfarice** [neozhaoliang/surround-view-system-introduction#87]
大佬的项目非常好！只是在实际应用中设置目标点和测量距离有一定的局限，如何改进可以自动对齐拼接呢？我现在的想法是通过检测棋盘格的四个顶点计算透视变换矩阵，然后检测重叠部分的棋盘格或矩形框来对齐。不知是否可行，应该怎么操作？
还有网上传说的通过特征匹配来对齐拼接的方法大佬有没有研究过？

**Comment by neozhaoliang** [comment]
我期待自动标定方法的出现。我认为手动选择标志点是很笨的办法，甚至摆标定板应该都是多余的。最好是能在马路上根据道路标识线自动标定。
