### ISSUE TITLE
Run_Live_Demo.py does not work in Windows 10

### ISSUE THREAD

**Issue by lsieczka** [neozhaoliang/surround-view-system-introduction#88]
Trying to get Run_Live_Demo.py to work in Windows 10 running Python 3.12.2 (tags/v3.12.2:6abddd9, Feb  6 2024, 21:26:36) [MSC v.1937 64 bit (AMD64)], I have OpenCV 4.9.0.

When I run Run_Live_Demo.py, the attached webcam turns on, but I do not see a pop-up with a birds eye view of the car with my camera in it. I can run run_get_projection_maps.py and that works fine, but for some reason not Run_Live_Demo.py

My webcam is index 1. There are no errors - as far as I can tell.

Any ideas?

**Comment by lsieczka** [comment]
I tried the same code on Ubuntu 18.04.6 LTS using Visual Studio Code. I can view the camera (index 4) using your test_cameras.py utility and the camera works great. OpenCV is version 3.2.0 and Python is version 3.6.9

![image](https://github.com/neozhaoliang/surround-view-system-introduction/assets/40127318/9364c609-29f4-4840-8265-a16477419011)

Thanks again, any help is appreciated.

**Comment by neozhaoliang** [comment]
Hi, do you mean that you have all four cameras correctly installed, and you can open each of them individually, but cannot see the birdview image?

**Comment by lsieczka** [comment]
Hello! Yes, I have 4 web cameras plugged into a laptop. I used your tool to get their index numbers and was trying to run them in run_live_demo.py, but can't seem to get past that "Cannot open camera" error. All the cameras just say cannot open camera #.

Is there maybe a version of something I might have wrong?

**Comment by neozhaoliang** [comment]
wait, you are using webcameras? Not quite sure but I guess this kind of camera is not supported? Because this project assumes you are using USB or CSI cameras. I

**Comment by lsieczka** [comment]
I see. That completely makes sense. Would it be hard to modify the code to use an external http (IP Camera)? I would like to eventually use a URL like 'http://192.168.0.90/mjpg/video.mjpg'. The eventual goal of this would be to try using your code on a shiploader. It's a huge machine that loads vessels. 
![image](https://github.com/neozhaoliang/surround-view-system-introduction/assets/40127318/860e3008-7a5e-4870-a35d-e36fd07d8821)
