### ISSUE TITLE
能否提供下其他方向的scale和shift

### ISSUE THREAD

**Issue by wqk151** [neozhaoliang/surround-view-system-introduction#89]
您好，我使用您的样例数据想跑通下流程，发下scale和shift不好调，特别是left方向效果一直调不好，能否提供下您这个效果中其他方向的scale和shift，谢谢！！

**Comment by neozhaoliang** [comment]
它们在配置文件里面可以看到，例如
https://github.com/neozhaoliang/surround-view-system-introduction/blob/master/yaml/right.yaml#L28-L37
