### ISSUE TITLE
权重矩阵定时更新

### ISSUE THREAD

**Issue by winterhorse** [neozhaoliang/surround-view-system-introduction#9]
请教一个问题，实际场景中由于行驶环境不同导致光照不一样，那么亮度均衡和权重矩阵是不是要实时更新呢？还有就是是应该先融合拼缝后亮度均衡还是反过来？

**Comment by neozhaoliang** [comment]
1. 权重矩阵是恒定的，只在标定时计算一次，然后保存好。
2. 亮度均衡是每一帧都要计算一次，比较费资源，所以市面上产品大多数都是用一个固定的 tone mapping 函数。
3. 顺序无所谓。
