### ISSUE TITLE
因为比较高的物体离车比较近导致的重叠区域有重影、图像跳跃的问题是不可避免的吗？有没有办法优化？

### ISSUE THREAD

**Issue by notfarice** [neozhaoliang/surround-view-system-introduction#90]

**Comment by neozhaoliang** [comment]
目前这种两个图像加权融合的方案恐怕避免不了这个问题。

我相信可以用 nn 来解决。看你的成本和架构了。只为优化图像走一个 nn 似乎不太划算。

**Comment by fenguangyi** [comment]
抱歉，我是新手，我也遇到了类似的问题，停车位旁边有水泥柱，处于前视相机和左视相机的交接处，然后拼接后重叠区域有重影，这是无法避免的？大佬你说可以用nn来解决，有没有可以参考的工作或者用来搜索的关键词推荐？感谢感谢

**Comment by fenguangyi** [comment]
或者有没有类似于这样的方案，将鱼眼矫正后的前后左右图像进行拼接，然后再进行单应矩阵变换？这样是否可行呢？

**Comment by neozhaoliang** [comment]
基于加权的方法无法做到完全去除重影。你可能需要训练一个网络，能够将两张有重叠区域的图片融合拼起来。这就不是我熟悉的了。

**Comment by fenguangyi** [comment]
非常感谢，看来需要重新想个办法

**Comment by neozhaoliang** [comment]
可以关注一下最新的图像融合方面的进展。传统的 CV 方法应该是过时了。
