### ISSUE TITLE
拼接后的图像内外参数以及世界坐标系相关

### ISSUE THREAD

**Issue by gopin95** [neozhaoliang/surround-view-system-introduction#91]
作者您好，有两个疑问。1.拼接后的图像只有透视矩阵，没有拼接图像的内外参数，请问这个拼接后的图像内外参数需要怎么求解呢。
2.拼接后的图形每一百个像素间隔相当于1m，通过像素位置是否可以求物体目标到车体的真实距离？但是鸟瞰图丧失了高度信息，是否可以通过相机的内外参数进行获取呢？

**Comment by neozhaoliang** [comment]
> "没有拼接图像的内外参数"

这是什么参数?

> 是否可以通过相机的内外参数进行获取呢？

你有一个射影矩阵，将像素转化为地面点，这个可以用来计算距离。

**Comment by 1kepingguo** [comment]
> 作者您好，有两个疑问。1.拼接后的图像只有透视矩阵，没有拼接图像的内外参数，请问这个拼接后的图像内外参数需要怎么求解呢。 2.拼接后的图形每一百个像素间隔相当于1m，通过像素位置是否可以求物体目标到车体的真实距离？但是鸟瞰图丧失了高度信息，是否可以通过相机的内外参数进行获取呢？

您好，请问可以加个联系方式交流下嘛，我也在学习这个
v:wulgdelianglai
