### ISSUE TITLE
拼接后图形的中心点是否与车辆中心重合？

### ISSUE THREAD

**Issue by gopin95** [neozhaoliang/surround-view-system-introduction#92]
在标定过程中，怎么操作才能确保拼接后图像中心点与车辆中心点保持重合呢？

**Comment by dota2015** [comment]
可以做偏移

**Comment by neozhaoliang** [comment]
如果你的参数设置是上下 / 左右分别对称的，那么理论上鸟瞰图的中心就是车辆的中心。

**Comment by neozhaoliang** [comment]
那样的话需要对代码做一些的改动。你需要自己设置 param_settings.py 里的各种参数，计算每个画面投影在鸟瞰图里的位置。
