### ISSUE TITLE
运行run_live_demo.py时程序能够正常运行，但得到的鸟瞰图是黑屏

### ISSUE THREAD

**Issue by Leooncode** [neozhaoliang/surround-view-system-introduction#95]
老师您好，我在Windows11上运行run_live_demo.py时程序能够正常运行，但得到的鸟瞰图是黑屏，请问该如何解决呢？
![6f41d63ac4ac1ef515c8859b0c166cd](https://github.com/neozhaoliang/surround-view-system-introduction/assets/49118905/bd5ccc09-79b3-4dd9-aae9-87a8c10aaec6)
![52526e16c4ecab4626eaa3870d71465](https://github.com/neozhaoliang/surround-view-system-introduction/assets/49118905/c518291e-ae19-4323-8c4b-3d7610f8039c)

**Comment by neozhaoliang** [comment]
你看看你的 fps，很明显你的画面读进来的就是黑色。

**Comment by Leooncode** [comment]
老师，我在检查代码时发现运行时的分辨率和相机yaml文件的分辨率一直不匹配，如下图中我yaml文件中相机分辨率为（960， 640），但这个地方一直为（320， 240），cv2.CAP_PROP_FRAME_WIDTH也无法修改，请问是什么问题呢？
![image](https://github.com/neozhaoliang/surround-view-system-introduction/assets/49118905/b0867f6f-a395-4331-8e50-7e455d961e8c)

**Comment by neozhaoliang** [comment]
查查你的相机支持哪些分辨率

**Comment by Leooncode** [comment]
谢谢老师的解答，还有一个问题经常遇到的，看issue中也有不少人遇到但没有解决，就是如下图所示，这个问题有时候会出现，有时候却能够正常运行，请问老师这个问题怎么解决呢？
![image](https://github.com/neozhaoliang/surround-view-system-introduction/assets/49118905/27a49065-fb52-4885-a6fb-862df197125c)

**Comment by neozhaoliang** [comment]
这是一个我没有遇到过的问题，所以我也不清楚原因。也许你可以问问那些遇到这个问题的人？
我怀疑是因为 usb 相机不稳定，会有设备号变化的现象导致的。但我不确定。

**Comment by Leooncode** [comment]
谢谢老师的耐心解答~
