### ISSUE TITLE
Ubuntu版本兼容性问题

### ISSUE THREAD

**Issue by shoyuan** [neozhaoliang/surround-view-system-introduction#96]
您好，请问可以支持ubuntu 20.04吗？如果无法兼容的话是因为哪个依赖不支持呢?

**Comment by neozhaoliang** [comment]
支持。依赖的话可能主要注意一下 opencv 和 qt. 我不记得我当时用的版本了。但是 cv 用 4.0 似乎是可以的。

**Comment by augsh** [comment]
我的就是Ubuntu20.04，工程是可以运行的
