### ISSUE TITLE
关于像素与实际距离对应关系

### ISSUE THREAD

**Issue by 1kepingguo** [neozhaoliang/surround-view-system-introduction#97]
老师您好，我对您所说的“为方便计算我们让每个像素对应 1 厘米”，然后设置shiftWidth以及shiftHeight的过程有点疑惑，请问如何保证一个像素对应一厘米的呢？还麻烦老师指教。
再提一句，您实在是太强了，不管是项目的实现还是您的回答，让人深深折服。

**Comment by neozhaoliang** [comment]
> 请问如何保证一个像素对应一厘米的呢？

这是个大概的说法，在投影变换下地面上的距离和像素距离不是 1 比 1 的关系，在车附近差不多是这样，在远处不是这样。

**Comment by 1kepingguo** [comment]
好的， 感谢您耐心指教。

**Comment by 1kepingguo** [comment]
我还想请教下，您之前提到过，”如果在一个嵌入式平台开发商业版本的话，为了效率考虑要避免频繁分配和销毁内存，所以把对每种图像（原始/校正/投影/鸟瞰)放在一个全局的命名空间里面，各自使用一块固定的内存，使用np.copyto或者cv: : copyTo来修改“，这个各自使用一块固定的内存应该怎么实现？麻烦老师

**Comment by neozhaoliang** [comment]
直接声明一个全局变量就行

**Comment by 1kepingguo** [comment]
> 直接声明一个全局变量就行
请问我可以理解为将每个线程的图像缓冲区（deque容器）封装在在全局变量的类中或者命名空间中吗？这样只用在开始的时候为全局对象分配一次内存。
并且在这个类中为他设置stop和process的互斥锁，防止外部更改内存。
感谢您的解答。

**Comment by 1kepingguo** [comment]
请问我可以理解为将每个线程的图像缓冲区（deque容器）封装在在全局变量的类中或者命名空间中吗？这样只用在开始的时候为全局对象分配一次内存。
并且在这个类中为他设置stop和process的互斥锁，防止外部更改内存。
感谢您的解答。

**Comment by Quentin-xue** [comment]
@neozhaoliang 
你好，能加个联系方式不？我的微信是：18603027764
麻烦了
