### ISSUE TITLE
关于联合标定的位置问题

### ISSUE THREAD

**Issue by augsh** [neozhaoliang/surround-view-system-introduction#98]
首先感谢您的开源和付出！

我看到联合标定部分的文档中，提到了标定板内侧边缘与车辆左右两侧的距离以及与车辆前后方的距离，这是不是意味着车辆必须停在标定布的的正中心，不能斜也不能偏？对于乘用车来说，在工厂机械操控下应该可以实现这一点，但对于线下的车辆来说，车辆停放会很容易出现误差，该怎么处理呢？

**Comment by neozhaoliang** [comment]
> 这是不是意味着车辆必须停在标定布的的正中心，不能斜也不能偏?

理论上可以不是，但是那样的话程序中就会出现更多的距离参数，更加复杂了。

> 但对于线下的车辆来说，车辆停放会很容易出现误差，该怎么处理呢?

我是用卷尺量的。

**Comment by augsh** [comment]
@neozhaoliang 感谢！
