### ISSUE TITLE
关于线程同步问题

### ISSUE THREAD

**Issue by Ironson233** [neozhaoliang/surround-view-system-introduction#99]
作者您好，
我目前使用ip摄像头，用rtsp取流，在实时播放拼接画面时遇到一个问题，应该是与缓存区有关，但不知具体问题点怎么产生的，想请教一下：
因为摄像头顺序是前后左右，不知是因为缓存区也按该顺序执行，还是说一开始连接摄像头有时间间隔，呈现出的4个相机画面按右左后前的顺序延迟依次递增，本身每个画面无卡顿，但就是同步着延迟，由于对信号量和互斥锁这部分不是很了解，能烦请指正一下导致该情况的可能原因吗？谢谢

**Comment by neozhaoliang** [comment]
你的意思是你的 4 个摄像头是在一个线程里面按照顺序抓取的？

**Comment by Ironson233** [comment]
> 你的意思是你的 4 个摄像头是在一个线程里面按照顺序抓取的？

不是的，我只是将usb相机换成了ip相机，还是分开的线程抓取/处理的

**Comment by neozhaoliang** [comment]
hmm，这个问题我目前解答不了，我没有这方面的经验。但是原因应该和信号量、互锁是没有关系的。
